# Generated by Django 4.2.16 on 2024-12-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestmixes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmix',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guest_mix_images/'),
        ),
        migrations.AlterField(
            model_name='guestmix',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guestmix',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guestmix',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guestmix',
            name='upload_date',
            field=models.DateField(),
        ),
    ]
