# Generated by Django 4.2.16 on 2024-12-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestmixes', '0002_guestmix_image_alter_guestmix_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmix',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
