# Generated by Django 4.2.16 on 2024-12-12 11:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestmixes', '0003_guestmix_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmix',
            name='audio_path',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guestmix',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
