# Generated by Django 4.2.16 on 2024-12-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestmixes', '0004_alter_guestmix_audio_path_alter_guestmix_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestmix',
            name='audio_path',
            field=models.FileField(upload_to='guest_mixes/'),
        ),
        migrations.AlterField(
            model_name='guestmix',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guest_mix_images/'),
        ),
    ]
